name: CI/CD for Cool-Graph

on:
  push:
    branches:
      - main 
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        python-version: 3.8
        environment-file: environment.yml
        activate-environment: cool-graph-env

    - name: Install build tools and dependencies
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate cool-graph-env
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install build twine

    - name: Build and publish package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate cool-graph-env
        python -m build
        python -m twine upload --repository-url https://pypi.org/project/cool-graph/ dist/*
